import re

with open("stress-test-report.html", "r", encoding="utf-8") as f:
    html = f.read()

html = re.sub(r'<div class="header-badge.*?>(.*?)</div>', r'<div class="header-badge {VERDICT_CLASS}">\n                {BADGE_TEXT}\n            </div>', html, flags=re.DOTALL)
html = html.replace('<div class="stat-value">4</div>', '<div class="stat-value">{TOTAL_REQUESTS}</div>')
html = html.replace('<div class="stat-value">75.0%</div>', '<div class="stat-value">{SUCCESS_RATE}%</div>')
html = html.replace('<div class="stat-sub">1 errors / 3 success</div>', '<div class="stat-sub">{FAIL_COUNT} errors / {SUCCESS_COUNT} success</div>')
html = html.replace('<div class="stat-value">~0s</div>', '<div class="stat-value">{DURATION_SEC}s</div>')
html = html.replace('<div class="stat-value">~13.3</div>', '<div class="stat-value">{THROUGHPUT}</div>')

html = re.sub(r'<div class="bar-fill fast" .*?>.*?</div>', r'<div class="bar-fill fast" style="width:{PCT_FAST}%">{COUNT_FAST} req</div>', html)
html = re.sub(r'<div class="bar-fill medium" .*?>.*?</div>', r'<div class="bar-fill medium" style="width:{PCT_MEDIUM}%">{COUNT_MEDIUM} req</div>', html)
html = re.sub(r'<div class="bar-fill slow" .*?>.*?</div>', r'<div class="bar-fill slow" style="width:{PCT_SLOW}%">{COUNT_SLOW} req</div>', html)
html = re.sub(r'<div class="bar-fill very-slow" .*?>.*?</div>', r'<div class="bar-fill very-slow" style="width:{PCT_VERY_SLOW}%">{COUNT_VERY_SLOW} req</div>', html)

html = re.sub(r'<div class="value" style="color:var\(--accent-green\)">.*?ms</div>', r'<div class="value" style="color:var(--accent-green)">{MIN}ms</div>', html, count=1)
html = re.sub(r'<div class="value" style="color:var\(--accent-blue\)">.*?ms</div>', r'<div class="value" style="color:var(--accent-blue)">{AVG}ms</div>', html, count=1)
html = re.sub(r'<div class="value" style="color:var\(--accent-orange\)">.*?ms</div>', r'<div class="value" style="color:var(--accent-orange)">{MAX}ms</div>', html, count=1)
html = re.sub(r'<div class="value" style="color:var\(--accent-blue\)">.*?ms</div>', r'<div class="value" style="color:var(--accent-blue)">{P90}ms</div>', html, count=1)
html = re.sub(r'<div class="value" style="color:var\(--accent-orange\)">.*?ms</div>', r'<div class="value" style="color:var(--accent-orange)">{P95}ms</div>', html, count=1)
html = re.sub(r'<div class="value" style="color:var\(--accent-red\)">.*?ms</div>', r'<div class="value" style="color:var(--accent-red)">{P99}ms</div>', html, count=1)

html = re.sub(r'<div class="value" style="color:var\(--accent-red\)">.*?%</div>', r'<div class="value" style="color:var(--accent-red)">{ERROR_RATE}%</div>', html, count=1)
html = re.sub(r'<div class="value" style="color:var\(--accent-purple\)">.*?/100</div>', r'<div class="value" style="color:var(--accent-purple)">{SCORE}/100</div>', html, count=1)

html = re.sub(r'<div class="verdict-emoji">.*?</div>', r'<div class="verdict-emoji">{VERDICT_EMOJI}</div>', html)
html = re.sub(r'<div class="verdict-title">.*?</div>', r'<div class="verdict-title">STRESS TEST: {VERDICT_TEXT}</div>', html)
html = re.sub(r'<div class="verdict-text">.*?</div>', r'<div class="verdict-text">\n                {TOTAL_REQUESTS} requests đã thực hiện. {SUCCESS_COUNT} thành công, {FAIL_COUNT} lỗi. \n                Error rate: {ERROR_RATE}%. Throughput: {THROUGHPUT} req/s. \n                Avg response time: {AVG}ms.\n            </div>', html, flags=re.DOTALL)

html = re.sub(r'<div class="value" style="font-size:16px">2026-03-23</div>', r'<div class="value" style="font-size:16px">{SHORT_DATE}</div>', html)
html = re.sub(r'<div class="value" style="font-size:14px">2026-03-23 08:58:28</div>', r'<div class="value" style="font-size:14px">{DATE_STR}</div>', html)
html = re.sub(r'<p>Generated by JMeter Reporter • 2026-03-23</p>', r'<p>Generated by Java StressTest • {SHORT_DATE}</p>', html)

html = re.sub(r'const chartData = \[.*?\];', r'const chartData = {CHART_DATA};', html)

html = html.replace("\\", "\\\\")

java_code = """package core_app.util;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.Duration;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.ConcurrentLinkedQueue;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;

public class StressTest {

    private static final String TARGET_URL = "https://unplanked-inculpably-malorie.ngrok-free.dev/";
    private static final int CONCURRENT_USERS = 200;
    private static final int TOTAL_REQUESTS = 1000; // Giới hạn 1000 request trước cho đỡ tốn thời gian nha

    public static void main(String[] args) {
        System.out.println("Bắt đầu Stress Test Tạo Đơn Hàng...");
        System.out.println("Mục tiêu: " + (TARGET_URL.endsWith("/") ? TARGET_URL + "api/orders" : TARGET_URL + "/api/orders"));
        System.out.println("Số luồng đồng thời: " + CONCURRENT_USERS);
        System.out.println("Tổng số request: " + TOTAL_REQUESTS);

        ExecutorService executor = Executors.newFixedThreadPool(CONCURRENT_USERS);
        HttpClient httpClient = HttpClient.newBuilder()
                .connectTimeout(Duration.ofSeconds(10))
                .build();

        AtomicInteger successCount = new AtomicInteger(0);
        AtomicInteger failureCount = new AtomicInteger(0);
        ConcurrentLinkedQueue<Long> responseTimes = new ConcurrentLinkedQueue<>();

        long startTime = System.currentTimeMillis();

        for (int i = 0; i < TOTAL_REQUESTS; i++) {
            executor.submit(() -> {
                long reqStart = System.currentTimeMillis();
                try {
                    String targetApiUrl = TARGET_URL.endsWith("/") ? TARGET_URL + "api/orders"
                            : TARGET_URL + "/api/orders";
                    String jsonBody = "{" +
                            "\\\"totalAmount\\\": 50000," +
                            "\\\"status\\\": \\\"PENDING\\\"," +
                            "\\\"paymentProof\\\": \\\"\\\"," +
                            "\\\"items\\\": [" +
                            "    {\\\"id\\\": \\\"M001\\\", \\\"name\\\": \\\"Vitamin C\\\", \\\"price\\\": 50000, \\\"qty\\\": 1}" +
                            "]" +
                            "}";

                    HttpRequest request = HttpRequest.newBuilder()
                            .uri(URI.create(targetApiUrl))
                            .header("Content-Type", "application/json")
                            .POST(HttpRequest.BodyPublishers.ofString(jsonBody))
                            .build();

                    HttpResponse<String> response = httpClient.send(request, HttpResponse.BodyHandlers.ofString());
                    long reqEnd = System.currentTimeMillis();
                    responseTimes.add(reqEnd - reqStart);

                    if (response.statusCode() == 200) {
                        successCount.incrementAndGet();
                    } else {
                        failureCount.incrementAndGet();
                        System.out.println("Lỗi " + response.statusCode() + ": " + response.body());
                    }
                } catch (Exception e) {
                    long reqEnd = System.currentTimeMillis();
                    responseTimes.add(reqEnd - reqStart);
                    failureCount.incrementAndGet();
                }
            });
        }

        executor.shutdown();
        try {
            executor.awaitTermination(10, TimeUnit.MINUTES);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        long endTime = System.currentTimeMillis();
        long durationMs = endTime - startTime;

        System.out.println("=========================================");
        System.out.println("KẾT QUẢ STRESS TEST");
        System.out.println("Thời gian thực thi: " + durationMs + " ms");
        System.out.println("Số request thành công (Mã 200): " + successCount.get());
        System.out.println("Số request thất bại: " + failureCount.get());
        System.out.println("Tốc độ trung bình: " + ((TOTAL_REQUESTS * 1000L) / durationMs) + " requests/giây");
        System.out.println("=========================================");

        System.out.println("Đang tạo HTML report...");
        generateReport(successCount.get(), failureCount.get(), durationMs, responseTimes);
        System.out.println("Tạo HTML report thành công. Hãy mở file stress-test-report.html để xem.");
    }

    private static void generateReport(int successCount, int failureCount, long durationMs, ConcurrentLinkedQueue<Long> responseTimesQueue) {
        int totalRequests = successCount + failureCount;
        List<Long> responseTimes = new ArrayList<>(responseTimesQueue);
        Collections.sort(responseTimes);

        long min = responseTimes.isEmpty() ? 0 : responseTimes.get(0);
        long max = responseTimes.isEmpty() ? 0 : responseTimes.get(responseTimes.size() - 1);
        long sum = responseTimes.stream().mapToLong(Long::longValue).sum();
        long avg = responseTimes.isEmpty() ? 0 : sum / responseTimes.size();

        long p90 = responseTimes.isEmpty() ? 0 : responseTimes.get((int) (responseTimes.size() * 0.90));
        long p95 = responseTimes.isEmpty() ? 0 : responseTimes.get((int) (responseTimes.size() * 0.95));
        long p99 = responseTimes.isEmpty() ? 0 : responseTimes.get((int) (responseTimes.size() * 0.99));

        double successRate = totalRequests == 0 ? 0 : (successCount * 100.0) / totalRequests;
        double errorRate = totalRequests == 0 ? 0 : (failureCount * 100.0) / totalRequests;
        double throughput = durationMs == 0 ? 0 : (totalRequests * 1000.0) / durationMs;
        double durationSec = durationMs / 1000.0;

        int countFast = 0; 
        int countMedium = 0; 
        int countSlow = 0; 
        int countVerySlow = 0; 

        for (long rt : responseTimes) {
            if (rt < 200) countFast++;
            else if (rt < 500) countMedium++;
            else if (rt < 1000) countSlow++;
            else countVerySlow++;
        }

        double pctFast = totalRequests == 0 ? 0 : (countFast * 100.0) / totalRequests;
        double pctMedium = totalRequests == 0 ? 0 : (countMedium * 100.0) / totalRequests;
        double pctSlow = totalRequests == 0 ? 0 : (countSlow * 100.0) / totalRequests;
        double pctVerySlow = totalRequests == 0 ? 0 : (countVerySlow * 100.0) / totalRequests;
        
        int score = (int)(100 - (errorRate) - (avg > 500 ? 10 : 0) - (pctVerySlow > 5 ? 10 : 0));
        if (score < 0) score = 0;

        StringBuilder chartDataBuilder = new StringBuilder("[");
        int step = Math.max(1, responseTimes.size() / 100);
        for (int i = 0; i < responseTimes.size(); i += step) {
            chartDataBuilder.append(responseTimes.get(i)).append(",");
        }
        if (chartDataBuilder.length() > 1) {
            chartDataBuilder.setLength(chartDataBuilder.length() - 1);
        }
        chartDataBuilder.append("]");

        String dateStr = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
        String shortDate = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));

        String verdictClass = errorRate < 5 ? "pass" : (errorRate < 20 ? "warn" : "fail");
        String verdictEmoji = errorRate < 5 ? "✅" : (errorRate < 20 ? "⚠️" : "❌");
        String verdictText = errorRate < 5 ? "SUCCESS" : (errorRate < 20 ? "WARNING" : "FAILED");
        String badgeText = errorRate < 5 ? "✅ Healthy" : (errorRate < 20 ? "⚠️ Degraded" : "❌ Critical");

        String template = \"\"\"TEMPLATE_PLACEHOLDER\"\"\";

        String htmlResult = template
            .replace("{VERDICT_CLASS}", verdictClass)
            .replace("{BADGE_TEXT}", badgeText)
            .replace("{TOTAL_REQUESTS}", String.valueOf(totalRequests))
            .replace("{SUCCESS_RATE}", String.format(java.util.Locale.US, "%.1f", successRate))
            .replace("{DURATION_SEC}", String.format(java.util.Locale.US, "%.2f", durationSec))
            .replace("{THROUGHPUT}", String.format(java.util.Locale.US, "%.1f", throughput))
            .replace("{FAIL_COUNT}", String.valueOf(failureCount))
            .replace("{SUCCESS_COUNT}", String.valueOf(successCount))
            .replace("{COUNT_FAST}", String.valueOf(countFast))
            .replace("{COUNT_MEDIUM}", String.valueOf(countMedium))
            .replace("{COUNT_SLOW}", String.valueOf(countSlow))
            .replace("{COUNT_VERY_SLOW}", String.valueOf(countVerySlow))
            .replace("{PCT_FAST}", String.format(java.util.Locale.US, "%.1f", pctFast))
            .replace("{PCT_MEDIUM}", String.format(java.util.Locale.US, "%.1f", pctMedium))
            .replace("{PCT_SLOW}", String.format(java.util.Locale.US, "%.1f", pctSlow))
            .replace("{PCT_VERY_SLOW}", String.format(java.util.Locale.US, "%.1f", pctVerySlow))
            .replace("{MIN}", String.valueOf(min))
            .replace("{AVG}", String.valueOf(avg))
            .replace("{MAX}", String.valueOf(max))
            .replace("{P90}", String.valueOf(p90))
            .replace("{P95}", String.valueOf(p95))
            .replace("{P99}", String.valueOf(p99))
            .replace("{ERROR_RATE}", String.format(java.util.Locale.US, "%.2f", errorRate))
            .replace("{SCORE}", String.valueOf(score))
            .replace("{VERDICT_EMOJI}", verdictEmoji)
            .replace("{VERDICT_TEXT}", verdictText)
            .replace("{SHORT_DATE}", shortDate)
            .replace("{DATE_STR}", dateStr)
            .replace("{CHART_DATA}", chartDataBuilder.toString());

        try {
            Files.writeString(Paths.get("stress-test-report.html"), htmlResult);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}"""

java_code = java_code.replace("TEMPLATE_PLACEHOLDER", "\\n" + html)

with open("src/core_app/util/StressTest.java", "w", encoding="utf-8") as f:
    f.write(java_code)

print("SUCCESSFULLY REWRITTEN")
