# SIMULATOR CONFIGURATION
# You can adjust the values below without recompiling code

# Frequency of performing actions (milliseconds)
# Default: 10000ms (10 seconds)
simulator.interval.ms=1000

# Target endpoint to send orders
# Default: http://localhost:8080/api/orders
simulator.endpoint=https://unplanked-inculpably-malorie.ngrok-free.dev/api/orders

# Enable detailed logging
# Default: true
simulator.enable.log=true

# Enable/Disable each action type
# If disabled, the action will not be executed even if selected
simulator.enable.order=true
simulator.enable.inventory=true
simulator.enable.medicine=true

# Configuration for inventory updates
# Min/Max quantity when updating inventory (random value between these two values)
simulator.inventory.min.quantity=50
simulator.inventory.max.quantity=100

# Configuration for adding new products
# Initial stock quantity when adding new product
simulator.medicine.initial.quantity=100
